### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by cody-carlson** [teradyne-dev-workshops/caption-this-0109#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by JGT90** [comment]
Hi cody

**Comment by joel8800** [comment]
Here is my comment

**Comment by Daduc38** [comment]
Hi Team, I am In 👍

**Comment by cody-carlson-learning** [comment]
hooray! 🏆

**Comment by rbelleau88** [comment]
Hello

**Comment by ACaspeer** [comment]
Hello

**Comment by jgtres** [comment]
Hi

**Comment by AndreiTeradyne** [comment]
My first comment

**Comment by kbushe** [comment]
Hey

**Comment by ElMT2023** [comment]
First comment

**Comment by ghost** [comment]
Hi

**Comment by JoelUsername** [comment]
Here is my comment

**Comment by JameHann** [comment]
James has an account, now

**Comment by Raccoon137** [comment]
Hello Cody, I'm here as well

**Comment by frehiwotberhe** [comment]
Hi

**Comment by shtaudor** [comment]
I'm here :)
